name: Experience CI/CD
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Ubuntu
        run: |
          sudo apt update
          sudo apt install -y nodejs npm