name: Experience CI/CD
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Ubuntu
        run: |          
          cat /etc/ssh/sshd_config